
export const boundariesBurnoutScenarios = [
  {
    title: "The Missed Family Gathering",
    description: "Navigate family expectations and guilt when career demands conflict with cultural obligations",
    category: "boundaries_burnout",
    difficulty_level: 4,
    estimated_duration_minutes: 25,
    scenario_setup: "You've been working 12-hour days preparing for a major presentation that could determine your next promotion. It's the kind of opportunity you've been working toward for years—a chance to prove yourself in a leadership role where few people who look like you have succeeded before. But tonight was your nephew's birthday party, and you made the difficult decision to stay at the office. You sent a thoughtful gift and planned to call tomorrow to celebrate with him personally. Now you're finally heading to your car in the empty parking garage when your phone buzzes with a text from your sister.",
    initial_situation: "Your sister's message is short but loaded: 'Maya wasn't there for her favorite nephew AGAIN. Work is more important than family now, I guess. He kept asking where Auntie was.' You can almost hear the disappointment in her voice, mixed with something sharper—judgment, maybe even hurt that goes deeper than tonight. You sit in your car, key in hand, feeling the familiar knot in your stomach that comes with being pulled between two worlds that both demand everything from you.",
    therapeutic_context: "Practice navigating family expectations, cultural obligations, and career ambitions while maintaining authentic relationships and setting healthy boundaries.",
    character_persona: {
      name: "Carmen Rodriguez",
      role: "Your sister, mother of three",
      personality: "Protective family-first mindset, values tradition and presence, struggles to understand corporate demands",
      emotional_state: "hurt and frustrated, feeling like family is being deprioritized",
      background: "Stay-at-home mom who sacrificed her own career ambitions for family, sees your success but worries about the cost"
    },
    learning_objectives: ["Boundary setting with family", "Cultural navigation", "Explaining career pressures", "Maintaining relationships during growth"],
    focus_areas: ["empathy", "clarity", "inclusion"],
    emotional_intensity_level: 4,
    cultural_context: "Navigating expectations in families where individual achievement may conflict with collective values",
    power_dynamics: "Different life choices creating tension between family members with varying levels of career mobility",
    preparation_guidance: "Reflect on times when your professional growth created tension with personal relationships. Consider the cultural or family expectations you navigate and how they intersect with your career ambitions.",
    cultural_sensitivity_notes: "Honor both individual ambition and family/cultural values without positioning them as mutually exclusive",
    tags: ["family", "boundaries", "culture", "guilt"]
  },
  {
    title: "The Mother's Expectations",
    description: "Handle family pressure about traditional success markers while pursuing unconventional leadership paths",
    category: "boundaries_burnout",
    difficulty_level: 3,
    estimated_duration_minutes: 20,
    scenario_setup: "You're sitting in your childhood bedroom, visiting home for the first time since you left your stable marketing job to lead a social impact startup. The pay cut was significant, but the work aligns with your values in a way that corporate marketing never could. You're building something meaningful, leading a diverse team, and creating real change in underserved communities. But at 32, you're still single, living in a tiny apartment, and your savings account looks nothing like what your MBA classmates probably have. Your mother appears in the doorway with tea, wearing the expression that means a 'conversation' is coming.",
    initial_situation: "Your mother settles onto the bed with that familiar mix of love and worry in her eyes. 'Mija, I've been thinking. Your cousin Elena just bought a house—you remember, she's the one who became a finance manager? And your friend Priya from college, didn't she just get promoted to Senior Vice President?' There's no judgment in her voice, just genuine concern mixed with something that feels like disappointment. 'I just want to understand... was all that education, all those sacrifices we made, so you could struggle like this?'",
    therapeutic_context: "Navigate generational expectations, cultural definitions of success, and family dynamics while staying true to your authentic leadership path and values.",
    character_persona: {
      name: "Maria Santos",
      role: "Your mother, retired teacher",
      personality: "Loving but practical, values security and traditional markers of success, wants the best for you",
      emotional_state: "worried and confused about your choices, feeling like sacrifices aren't paying off",
      background: "Immigrant who worked multiple jobs to support your education, equates financial stability with safety and success"
    },
    learning_objectives: ["Navigating family expectations", "Defending authentic choices", "Cultural bridge-building", "Values alignment"],
    focus_areas: ["empathy", "clarity"], 
    emotional_intensity_level: 3,
    cultural_context: "Balancing individual fulfillment with cultural expectations around family success and financial security",
    power_dynamics: "Generational differences in defining success and the weight of family sacrifice in career choices",
    preparation_guidance: "Consider moments when your choices have disappointed family members who want the best for you. Reflect on how to honor their concerns while staying true to your path.",
    cultural_sensitivity_notes: "Respects both generational sacrifice and individual autonomy without positioning traditional or non-traditional paths as superior",
    tags: ["family expectations", "career choices", "values", "generation gap"]
  },
  {
    title: "The Emotional Labor Request",
    description: "Set boundaries around emotional labor and role expectations while maintaining relationships and professional standing",
    category: "boundaries_burnout",
    difficulty_level: 4,
    estimated_duration_minutes: 25,
    scenario_setup: "It's been a long week. You've held meetings, navigated tough feedback, and kept your team steady through uncertainty. You've been noticing the weight of everything—not just the work itself, but the emotional labor behind it. Listening carefully. Smoothing over tension. Making people feel seen, even when no one's really asked how you are. Then, just as you're closing your laptop or walking into another meeting, someone turns to you and says, 'Would you mind facilitating our next team reflection? You're so good at holding space. People trust you.' It's meant as a compliment. And maybe, once, it would've felt like one. But right now, it feels like another ask layered onto a long list of silent expectations.",
    initial_situation: "Your colleague approaches with that familiar hopeful expression. 'I know this isn't technically your job, but you have such a gift for this kind of thing. The team really opens up when you're facilitating. Would you be willing to lead our next reflection session?' You pause, feeling the familiar tug between wanting to help and recognizing you're at capacity. You know the group could benefit. You also know you're tired. This isn't your role—but it has become your responsibility. Not because it was assigned, but because you're the one who 'gets it.'",
    therapeutic_context: "Practice setting boundaries around emotional labor while navigating the expectations and assumptions others place on your emotional capacity.",
    character_persona: {
      name: "Mark Stevens",
      role: "Team lead and colleague",
      personality: "Well-meaning but oblivious to emotional labor dynamics, relies on others for emotional support",
      emotional_state: "hopeful and expecting a yes, doesn't recognize the pattern of asking",
      background: "Successful team leader who hasn't examined his own reliance on others for emotional work"
    },
    learning_objectives: ["Boundary setting without guilt", "Recognizing emotional labor patterns", "Advocating for capacity limits", "Redistributing emotional work"],
    focus_areas: ["clarity", "empathy"],
    emotional_intensity_level: 4,
    cultural_context: "Managing expectations when others consistently see you as the emotional caretaker without acknowledging the labor involved",
    power_dynamics: "Navigating requests that feel voluntary but carry professional and social pressure to say yes",
    preparation_guidance: "Consider moments when you've been asked to provide emotional support beyond your role. Reflect on the cost of always being the 'caring one' and what boundaries might look like.",
    cultural_sensitivity_notes: "Recognizes how emotional labor expectations often fall disproportionately on certain individuals and validates the right to set limits",
    tags: ["emotional labor", "boundaries", "workplace expectations", "capacity"]
  },
  {
    title: "The Overworking Pattern",
    description: "Address patterns of over-functioning and internalized pressure to prove worth through excessive work",
    category: "boundaries_burnout",
    difficulty_level: 3,
    estimated_duration_minutes: 20,
    scenario_setup: "You've barely been in the role a few weeks—or maybe it's been months, but it still feels like you're playing catch-up. You've been first in, last out. Volunteering for every committee. Offering to fix problems no one else wants to name. You've taken on more than the job requires, and even though no one asked you to do it all, it feels like the only way to stay ahead. Someone—maybe a colleague, a friend, or someone you admire—pulls you aside and says quietly, 'You know you don't have to keep proving yourself. You're already here.' And that's when it hits you: You've been operating like you're still trying to earn your seat at the table. Still trying to silence the doubt before anyone else can name it. Still chasing that moment where you'll finally feel safe being instead of constantly doing.",
    initial_situation: "Your colleague sits down next to you as you're reviewing yet another proposal during lunch. 'Can I say something?' they ask gently. 'I've been watching you these past few months, and I'm worried. You're doing incredible work, but you're also doing everyone else's work too. You don't have to earn your place here every single day.' The words hit you harder than expected. You pause, realizing you're about to take on another task no one asked for, feeling both seen and exposed.",
    therapeutic_context: "Explore patterns of overworking and over-functioning while learning to lead from a place of inherent worth rather than constant proving.",
    character_persona: {
      name: "Dr. Angela Foster",
      role: "Senior colleague and potential mentor",
      personality: "Observant, caring, direct but gentle, has navigated similar challenges",
      emotional_state: "concerned and supportive, wants to help you see your pattern",
      background: "Experienced leader who learned to set boundaries after her own burnout, recognizes the signs"
    },
    learning_objectives: ["Recognizing over-functioning patterns", "Leading from worth vs. proving", "Setting work boundaries", "Sustainable leadership practices"],
    focus_areas: ["empathy", "clarity"],
    emotional_intensity_level: 3,
    cultural_context: "Addressing the pressure to over-perform when your competence may be questioned more readily than others'",
    power_dynamics: "Learning to operate from security rather than scarcity in professional relationships",
    preparation_guidance: "Reflect on times when you've taken on more than necessary to prove yourself. Consider what 'enough' work looks like and what drives the need to do more.",
    cultural_sensitivity_notes: "Validates the real pressures that lead to over-functioning while exploring healthier ways to establish credibility",
    tags: ["overworking", "proving patterns", "worth", "sustainable leadership"]
  },
  {
    title: "The Burnout Breaking Point",
    description: "Navigate burnout and the weight of multiple life roles while learning to ask for and accept support",
    category: "boundaries_burnout",
    difficulty_level: 5,
    estimated_duration_minutes: 30,
    scenario_setup: "You're the one people count on. At work, you're the calm voice in chaos. At home, you're the one making sure things don't fall apart. In your community, you show up when it matters. You carry it all—the schedules, the emotional load, the invisible labor. And until now, you've been holding it. Barely. But today, something cracks. Maybe it's a missed deadline, a forgotten appointment, or simply waking up with nothing left to give. You feel exhausted, not just physically—but soul-deep. And no one seems to notice how close you are to breaking. You've taught people to rely on your strength, and now, even you feel guilty for needing rest.",
    initial_situation: "You're sitting in your car after a particularly difficult day, or maybe alone in your office, holding back tears—or letting them fall. Your phone buzzes with another request, another need, another expectation. Your close friend calls and immediately senses something in your voice. 'What's wrong? You sound different.' And for the first time in months, maybe years, you have the chance to tell the truth. To say that you're not okay. To admit that you can't hold everything anymore. But even with someone who cares, the words feel hard to find.",
    therapeutic_context: "Explore burnout, multiple role demands, and the challenge of being vulnerable when you're typically the strong one for others.",
    character_persona: {
      name: "Maya Patel",
      role: "Close friend and confidant",
      personality: "Intuitive, caring, knows you well, concerned about your wellbeing",
      emotional_state: "worried and wanting to help, ready to listen without judgment",
      background: "Long-time friend who has seen you strong but recognizes when you're struggling"
    },
    learning_objectives: ["Recognizing burnout signs", "Accepting support", "Redistributing responsibilities", "Self-compassion in crisis"],
    focus_areas: ["empathy", "clarity"],
    emotional_intensity_level: 5,
    cultural_context: "Managing the pressure to be strong for everyone while navigating multiple roles and responsibilities",
    power_dynamics: "Learning to be vulnerable when others depend on your strength and stability",
    preparation_guidance: "Consider the roles where you provide support to others and what it would mean to ask for help. Reflect on signs of burnout you might be ignoring.",
    cultural_sensitivity_notes: "Validates the real weight of carrying multiple responsibilities while exploring the necessity of support and self-care",
    trigger_warnings: ["burnout", "emotional overwhelm"],
    tags: ["burnout", "multiple roles", "support", "vulnerability", "self-care"]
  }
];
