
export const powerIdentityAdvancedScenarios = [
  {
    title: "Asserting Credibility Under Scrutiny",
    description: "Navigate questioning of your readiness for a major project while maintaining confidence and authority",
    category: "power_identity_politics",
    difficulty_level: 4,
    estimated_duration_minutes: 25,
    scenario_setup: "You're in a meeting space—perhaps a boardroom, virtual call, or unexpected hallway conversation. A senior executive has just questioned your readiness for a significant new project in a way that feels loaded with assumptions.",
    initial_situation: "A senior leader turns to you with a raised brow and slight head tilt, saying: 'This is a big project—are you sure you're ready for something like this?' The way they ask makes it clear you're the only one being questioned about readiness.",
    therapeutic_context: "Practice asserting credibility without defensiveness while navigating coded doubt and maintaining leadership presence under scrutiny.",
    character_persona: {
      name: "Senior Executive",
      role: "VP of Strategic Initiatives", 
      personality: "Skeptical, influential, tests others' confidence, potentially unconsciously biased",
      emotional_state: "questioning and slightly dismissive",
      background: "Established leader used to traditional approaches, may not recognize their bias patterns"
    },
    learning_objectives: ["Confidence assertion", "Handling microaggressions", "Leadership presence", "Professional advocacy"],
    focus_areas: ["empathy", "clarity", "inclusion"],
    emotional_intensity_level: 4,
    tags: ["power dynamics", "credibility", "leadership presence", "bias navigation"],
    cultural_context: "Workplace where underrepresentation creates extra scrutiny and pressure to prove worthiness",
    power_dynamics: "Senior-junior hierarchy with potential identity-based assumptions affecting perception of capability",
    trigger_warnings: ["workplace discrimination", "imposter syndrome triggers"],
    cultural_sensitivity_notes: "Scenario addresses common experiences of marginalized leaders facing disproportionate questioning of their qualifications"
  },
  {
    title: "Addressing Microaggression Denial", 
    description: "Respond when a colleague minimizes the impact of a microaggression you experienced",
    category: "power_identity_politics",
    difficulty_level: 5,
    estimated_duration_minutes: 20,
    scenario_setup: "You previously addressed a microaggression in a professional setting. Now in a follow-up conversation, the colleague is dismissing your experience and deflecting responsibility for the impact.",
    initial_situation: "Your colleague approaches you privately and says: 'Wow, I think you took it the wrong way. That's not what I meant.' They seem defensive and are minimizing the incident you previously addressed.",
    therapeutic_context: "Practice standing firm on impact versus intent while maintaining professional relationships and advocating for yourself without emotional exhaustion.",
    character_persona: {
      name: "Defensive Colleague",
      role: "Project Manager",
      personality: "Well-meaning but defensive, struggles with feedback about bias, prioritizes their intent over impact",
      emotional_state: "defensive and slightly uncomfortable",
      background: "Generally considers themselves progressive but has difficulty accepting when their actions cause harm"
    },
    learning_objectives: ["Impact vs intent navigation", "Self-advocacy", "Boundary setting", "Emotional regulation"],
    focus_areas: ["empathy", "clarity", "inclusion"],
    emotional_intensity_level: 5,
    tags: ["microaggressions", "impact vs intent", "self-advocacy", "difficult conversations"],
    cultural_context: "Workplace where marginalized individuals must navigate denial and gaslighting around their experiences",
    power_dynamics: "Peer-level interaction where one person's experience is being invalidated by another",
    trigger_warnings: ["gaslighting", "denial of discrimination"],
    cultural_sensitivity_notes: "Addresses the exhausting dynamic of having to defend the validity of one's own experience of bias"
  },
  {
    title: "Protecting Wellness Boundaries", 
    description: "Address a supervisor who repeatedly schedules meetings during your designated wellness time",
    category: "boundaries_burnout",
    difficulty_level: 3,
    estimated_duration_minutes: 15,
    scenario_setup: "You've clearly blocked wellness time in your calendar, but your supervisor keeps scheduling meetings during these periods. This has become a recurring pattern that's affecting your well-being.",
    initial_situation: "Your supervisor approaches you about yet another meeting request during your blocked wellness time, saying: 'I know you have something blocked, but this is really important. Can we just move your personal time this once?'",
    therapeutic_context: "Practice protecting personal boundaries while maintaining professional relationships and modeling healthy work-life integration.",
    character_persona: {
      name: "Well-Meaning Supervisor",
      role: "Department Director",
      personality: "Results-focused, caring but boundary-blind, doesn't fully grasp the importance of protected time",
      emotional_state: "rushed and slightly oblivious to the pattern",
      background: "Hardworking leader who often sacrifices personal time and unconsciously expects the same from others"
    },
    learning_objectives: ["Boundary enforcement", "Self-advocacy", "Professional communication", "Wellness prioritization"],
    focus_areas: ["empathy", "clarity"],
    emotional_intensity_level: 3,
    tags: ["boundaries", "wellness", "supervisor relationships", "self-preservation"],
    cultural_context: "Work environment where personal time is often seen as flexible or optional",
    power_dynamics: "Supervisor-employee dynamic where power imbalance makes boundary-setting challenging",
    preparation_guidance: "Reflect on your core wellness needs and practice language that's firm but collaborative"
  },
  {
    title: "Mediating Team Communication Conflict",
    description: "Intervene fairly when two team members have ongoing communication issues affecting team dynamics", 
    category: "team_dynamics",
    difficulty_level: 4,
    estimated_duration_minutes: 30,
    scenario_setup: "Two team members have been experiencing tension that's affecting the whole team. You've observed eye rolls, awkward silences, and dropped tasks when they work together. Cultural dynamics and communication styles may be contributing factors.",
    initial_situation: "You're meeting with both team members together. One starts by saying: 'I don't think they listen to anything I suggest, and when I try to give feedback, they just shut down.' The other responds defensively: 'I'm not shutting down, I just don't appreciate being micromanaged.'",
    therapeutic_context: "Practice mediating conflict with cultural sensitivity while maintaining team cohesion and addressing underlying power dynamics.",
    character_persona: {
      name: "Team Members in Conflict",
      role: "Senior Analyst & Marketing Coordinator", 
      personality: "Both well-intentioned but stuck in miscommunication patterns, different cultural communication styles",
      emotional_state: "frustrated and defensive on both sides",
      background: "Different backgrounds and communication approaches leading to mutual misunderstanding"
    },
    learning_objectives: ["Conflict mediation", "Cultural sensitivity", "Team dynamics", "Inclusive leadership"],
    focus_areas: ["empathy", "inclusion", "clarity"],
    emotional_intensity_level: 4,
    tags: ["conflict resolution", "team dynamics", "cultural awareness", "mediation"],
    cultural_context: "Diverse team where communication styles and cultural backgrounds create potential for misunderstanding",
    power_dynamics: "Peer-level conflict with potential seniority or cultural power imbalances",
    cultural_sensitivity_notes: "Consider how different cultural communication norms may be contributing to the conflict"
  },
  {
    title: "Engaging Silent Team Member",
    description: "Check in with a team member who consistently stays quiet in meetings and find ways to invite contribution",
    category: "inclusive_leadership", 
    difficulty_level: 2,
    estimated_duration_minutes: 15,
    scenario_setup: "A newer team member attends all meetings but never speaks up. They're engaged and taking notes, but you're wondering if they're holding back for a reason and want to create safe space for participation.",
    initial_situation: "You've asked for a brief one-on-one after a team meeting. The team member seems slightly nervous and says: 'I hope I'm not in trouble. I know I don't say much in meetings, but I'm definitely paying attention and learning a lot.'",
    therapeutic_context: "Practice inclusive leadership by creating psychological safety and inviting contribution without pressure or assumptions.",
    character_persona: {
      name: "Quiet Team Member",
      role: "Junior Developer",
      personality: "Thoughtful, observant, cautious about speaking up, wants to contribute but uncertain about when/how",
      emotional_state: "slightly anxious but eager to please",
      background: "New to the team and workplace culture, may have learned that speaking up can have costs"
    },
    learning_objectives: ["Inclusive leadership", "Psychological safety", "Cultural sensitivity", "Team engagement"],
    focus_areas: ["empathy", "inclusion"],
    emotional_intensity_level: 2,
    tags: ["inclusion", "team engagement", "psychological safety", "new employees"],
    cultural_context: "Workplace where participation norms may not align with all cultural communication styles",
    power_dynamics: "Manager-employee dynamic where power imbalance may inhibit voice",
    preparation_guidance: "Approach with curiosity rather than assumptions about their silence"
  },
  {
    title: "Defending Recommendations to Leadership",
    description: "Respond when senior leadership questions your equity-focused recommendations without escalating conflict",
    category: "communication_feedback",
    difficulty_level: 5, 
    estimated_duration_minutes: 25,
    scenario_setup: "You're presenting an equity-focused initiative you've researched thoroughly to senior leadership. Your recommendations are being questioned in a way that feels dismissive of the underlying values.",
    initial_situation: "Midway through your presentation, a senior leader interrupts with a tight smile: 'That won't work here. We don't want to make things too political. Our culture is about merit, not special treatment.' The room shifts uncomfortably.",
    therapeutic_context: "Practice defending values-based recommendations with conviction while maintaining diplomatic relationships and strategic thinking.",
    character_persona: {
      name: "Resistant Senior Leader",
      role: "C-Suite Executive",
      personality: "Traditional, change-averse, sees equity work as potentially divisive, uses coded language",
      emotional_state: "skeptical and slightly dismissive",
      background: "Successful in traditional systems, may not recognize bias in current processes"
    },
    learning_objectives: ["Strategic communication", "Values advocacy", "Change management", "Executive presence"],
    focus_areas: ["clarity", "empathy", "inclusion"],
    emotional_intensity_level: 5,
    tags: ["change management", "executive communication", "equity advocacy", "strategic influence"],
    cultural_context: "Corporate environment where equity initiatives may face resistance framed as 'business concerns'",
    power_dynamics: "Significant power imbalance where junior person advocates for change to resistant senior leadership",
    trigger_warnings: ["discrimination denial", "coded bias language"],
    cultural_sensitivity_notes: "Addresses the challenge of advocating for equity in environments resistant to acknowledging systemic issues"
  },
  {
    title: "Reclaiming Credit for Your Ideas",
    description: "Address a situation where a colleague is taking credit for your idea in a team meeting",
    category: "authentic_leadership",
    difficulty_level: 3,
    estimated_duration_minutes: 20,
    scenario_setup: "You're in a team meeting where a colleague is presenting an idea you originally proposed in a previous brainstorm. They're receiving praise and momentum for what you recognize as your contribution.",
    initial_situation: "Your colleague finishes presenting 'their' idea and the team lead responds enthusiastically: 'This is exactly the kind of innovative thinking we need! Great work on developing this approach.' You feel your chest tighten as you recognize your own idea being attributed to someone else.",
    therapeutic_context: "Practice reclaiming credit professionally while maintaining team relationships and setting boundaries around intellectual contribution.",
    character_persona: {
      name: "Credit-Taking Colleague",
      role: "Marketing Specialist",
      personality: "Ambitious, may not realize the impact of their actions, comfortable taking space and credit", 
      emotional_state: "confident and pleased with the positive reception",
      background: "Used to receiving recognition, may unconsciously assume ideas become collective once shared"
    },
    learning_objectives: ["Professional advocacy", "Credit reclamation", "Boundary setting", "Team dynamics"],
    focus_areas: ["clarity", "empathy"],
    emotional_intensity_level: 3,
    tags: ["credit theft", "professional advocacy", "intellectual property", "team dynamics"],
    cultural_context: "Workplace where ideas can be easily appropriated and credit misattributed",
    power_dynamics: "Peer-level interaction where one person's contribution is being erased",
    preparation_guidance: "Practice language that reclaims credit without appearing petty or disruptive to team flow"
  }
];
