// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrefzfhfwebqcrdcygcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZWZ6Zmhmd2VicWNyZGN5Z2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzkwMDcsImV4cCI6MjA2NTI1NTAwN30.IqPv5I2pK6OYbXzaP2dxORHlsoVArWC3TqiJfWDnD6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);